//go:build !ignore_autogenerated

// Code in this file is hand-written to the same contract controller-gen would
// emit (DeepCopyInto/DeepCopy/DeepCopyObject) so the package needs no codegen
// toolchain to compile and satisfy runtime.Object.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *MinecraftServer) DeepCopyInto(out *MinecraftServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of the receiver.
func (in *MinecraftServer) DeepCopy() *MinecraftServer {
	if in == nil {
		return nil
	}
	out := new(MinecraftServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *MinecraftServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *MinecraftServerList) DeepCopyInto(out *MinecraftServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		l := make([]MinecraftServer, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&l[i])
		}
		out.Items = l
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *MinecraftServerList) DeepCopy() *MinecraftServerList {
	if in == nil {
		return nil
	}
	out := new(MinecraftServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *MinecraftServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies the receiver into out.
func (in *MinecraftServerSpec) DeepCopyInto(out *MinecraftServerSpec) {
	*out = *in
	if in.JavaFlags != nil {
		l := make([]string, len(in.JavaFlags))
		copy(l, in.JavaFlags)
		out.JavaFlags = l
	}
	if in.Args != nil {
		l := make([]string, len(in.Args))
		copy(l, in.Args)
		out.Args = l
	}
	if in.Env != nil {
		l := make([]EnvVar, len(in.Env))
		copy(l, in.Env)
		out.Env = l
	}
	out.Motd = in.Motd
	out.Rcon = in.Rcon
	out.Storage = in.Storage
	in.Resources.DeepCopyInto(&out.Resources)
	out.Lifecycle = in.Lifecycle
	out.Startup = in.Startup
	out.Idle = in.Idle
}

// DeepCopy returns a deep copy of the receiver.
func (in *MinecraftServerSpec) DeepCopy() *MinecraftServerSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies the receiver into out.
func (in *MinecraftServerStatus) DeepCopyInto(out *MinecraftServerStatus) {
	*out = *in
	out.Endpoint = in.Endpoint
	out.Players = in.Players
	if in.ReadySignalAt != nil {
		out.ReadySignalAt = in.ReadySignalAt.DeepCopy()
	}
	if in.Conditions != nil {
		l := make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&l[i])
		}
		out.Conditions = l
	}
}

// DeepCopy returns a deep copy of the receiver.
func (in *MinecraftServerStatus) DeepCopy() *MinecraftServerStatus {
	if in == nil {
		return nil
	}
	out := new(MinecraftServerStatus)
	in.DeepCopyInto(out)
	return out
}
